version: '3'

services:
  app-db:
    image: postgres:14.5-alpine
    container_name: app-db
    environment:
      - POSTGRES_PASSWORD=${APP_PG_PASS:?database password not set}
      - PGUSER=${APP_PG_USER:?database user not set}
      - POSTGRES_DB=$APP_DB_NAME
    ports:
      - $APP_PG_OUT_PORT:$APP_PG_PORT
    restart: unless-stopped
  gophermart:
    build:
      context: .
      dockerfile: ./docker/gophermart
    container_name: gophermart
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - app-db
    links:
      - app-db
      - accrual
    command: sh -c "until nc -z app-db $APP_PG_PORT; do sleep 1; done && ./gophermart"
  accrual:
    image: ubuntu:22.04
    container_name: accrual
    env_file: .env
    volumes:
      - ./cmd/accrual/:/usr/local/bin
    ports:
      - 8080:8080
    depends_on:
      - app-db
    links:
      - app-db
    command: sh -c "until nc -z app-db $APP_PG_PORT; do sleep 1; done && /usr/local/bin/accrual_linux_amd64"